const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

if (!API_KEY) {
    console.warn('Gemini API key not found. AI features will be disabled. Please add VITE_GEMINI_API_KEY to your .env file.');
}

// Helper to make direct API calls to Gemini
async function callGeminiAPI(prompt, systemInstruction = "") {
    if (!API_KEY) throw new Error("API Key missing");

    // Using the absolute most standard endpoint for compatibility
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${API_KEY}`;

    const payload = {
        contents: [
            {
                parts: [
                    { text: systemInstruction ? `${systemInstruction}\n\n${prompt}` : prompt }
                ]
            }
        ]
    };

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
    });

    if (!response.ok) {
        const errorData = await response.json();
        const errorMessage = errorData.error?.message || `API Error: ${response.status}`;
        console.error("Gemini API Error:", errorMessage);
        throw new Error(errorMessage);
    }

    const data = await response.json();
    if (!data.candidates || data.candidates.length === 0) {
        if (data.promptFeedback && data.promptFeedback.blockReason) {
            throw new Error(`Response blocked: ${data.promptFeedback.blockReason}`);
        }
        return "No response generated by AI.";
    }

    return data.candidates[0].content.parts[0].text;
}

// Eagle Yoga AI Consultant
export const chatWithEagleAI = async (message, conversationHistory = []) => {
    try {
        const systemInstruction = `You are Eagle Yoga AI... (Your yoga persona)`;

        // Simple context construction
        const historyText = conversationHistory.map(msg => `${msg.role}: ${msg.content}`).join('\n');
        const fullPrompt = `Running Conversation:\n${historyText}\nUser: ${message}\n\nRespond as Eagle Yoga AI.`;

        const response = await callGeminiAPI(fullPrompt, systemInstruction);
        return response;
    } catch (error) {
        console.error('Eagle AI Error:', error);
        return `Connection Error: ${error.message}. Please check your API key settings.`;
    }
};

// AI Health Assessment - Detailed Analysis
export const analyzeHealthProfile = async (healthData) => {
    try {
        const prompt = `Act as a world-class Medical Yoga Therapist. Analyze this health profile:
    ${JSON.stringify(healthData, null, 2)}
    Task: Generate a highly detailed Wellness Report (1000+ words).`;
        return await callGeminiAPI(prompt, "");
    } catch (error) {
        console.error('Health Analysis Error:', error);
        throw new Error(`Analysis failed: ${error.message}`);
    }
};

// Generate Personalized Diet Plan
export const generateDietPlan = async (userProfile) => {
    try {
        const prompt = `Create a 7-Day Sattvic Diet Plan for:
    ${JSON.stringify(userProfile, null, 2)}`;
        return await callGeminiAPI(prompt, "");
    } catch (error) {
        console.error('Diet Plan Error:', error);
        throw new Error(`Diet plan failed: ${error.message}`);
    }
};

// Generate Blog Content
export const generateBlogContent = async (topic) => {
    try {
        const prompt = `Write a deep blog post about: "${topic}". Length: 1000+ words.`;
        return await callGeminiAPI(prompt, "");
    } catch (error) {
        console.error('Blog Generation Error:', error);
        throw new Error(`Blog generation failed: ${error.message}`);
    }
};

export default {
    chatWithEagleAI,
    analyzeHealthProfile,
    generateDietPlan,
    generateBlogContent,
};
