/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function EagleModel(props) {
    const group = useRef();
    // NOTE: This usually expects a model at /eagle.glb. 
    // Since we don't have one, we might need to use a placeholder or the user needs to provide it.
    // However, I will try to use a procedural mesh if this fails or just set up the scene.
    // For now, I will create a "procedural" bird using simple meshes to ensure it works without external assets.

    return (
        <group ref={group} {...props} dispose={null}>
            {/* Body */}
            <mesh position={[0, 0, 0]} rotation={[0, 0, 0]}>
                <coneGeometry args={[0.5, 2, 32]} />
                <meshStandardMaterial color="#3E2723" />
            </mesh>
            {/* Head */}
            <mesh position={[0, 1.2, 0.3]}>
                <sphereGeometry args={[0.35, 32, 32]} />
                <meshStandardMaterial color="white" />
            </mesh>
            {/* Beak */}
            <mesh position={[0, 1.2, 0.6]} rotation={[1.5, 0, 0]}>
                <coneGeometry args={[0.1, 0.4, 32]} />
                <meshStandardMaterial color="gold" />
            </mesh>
            {/* Wings - Animated manually in useFrame usually */}
            <mesh position={[0.8, 0.5, 0]} rotation={[0, 0, -0.5]}>
                <boxGeometry args={[2, 0.2, 1]} />
                <meshStandardMaterial color="#3E2723" />
            </mesh>
            <mesh position={[-0.8, 0.5, 0]} rotation={[0, 0, 0.5]}>
                <boxGeometry args={[2, 0.2, 1]} />
                <meshStandardMaterial color="#3E2723" />
            </mesh>
        </group>
    );
}
